version: '3.7'

services:
  poc:
    build:
      context: ""
    volumes:
      - '.:/app'
      - '/node_modules'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    stdin_open: true