export const GET_LISTINGS_ACTION = 'GET_LISTINGS_ACTION';
export const GET_MY_LISTINGS_ACTION = 'GET_MY_LISTINGS_ACTION';
export const SELECTED_PRODUCT = 'SELECTED_PRODUCT';
export const LOGIN_IN  = 'LOGIN_IN';
export const LOGIN_OUT = 'LOGIN_OUT';
export const LOADING_SPINNER = 'LOADING_SPINNER';
export const STOP_LOADING_SPINNER = 'STOP_LOADING_SPINNER';